### PR TITLE
Small refactors and improvements

### PR DESCRIPTION
**Pull request by amirhakimnejad**
- Remove unused IMPLEMENTING parameter
- Fix a comment
- use `ConsentStatus` instead of `_consentStatus` within `InitComplete()` to make sure `OnStatusChanged` invokes on every change

### CODE REVIEW

**Comment by amirhakimnejad** [comment]
Does the thrid change make sense? Or am I missing something?

**Comment by binouze** [comment]
Hi @amirhakimnejad,
 
 - The IMPLEMENTING directive is there for me when I develop the plugin. I use Rider as IDE and it makes the code grey and disable auto-completion and error checking when not in an active directive. So I added this IMPLEMENTING to be able to code normally (most of time I don't forget to undef it 😅). If you have an IMPLEMENTING directive defined in your project I can change the name to prevent conflicts, maybe UMP_IMPLEMENTING or something like this.
 - In the `InitComplete()` function, the `_consentStatus` is set directly to not have any `OnStatusChanged` called before the initialisation process is complete. You can then retrieve the consent status in the `OnComplete` callback or in the `ConsentStatus` variable after initialisation. I think it's cleaner that way.

**Comment by binouze** [comment]
I just pushed an update with a rename of the IMPLEMENTING define (now it's UMP_IMPLEMENTING) and some fix on documentations.
I close the pull request for now. Feel free to contact me if you have any other problem.

**Comment by amirhakimnejad** [comment]
Thank you for the update and the answer

**Pull request closed without merging**
